### PR TITLE
Add Russian Localization

### PR DESCRIPTION
**Pull request by dpolyakov**
Hello.

I think it can be usefull

### CODE REVIEW

**Comment by jhauraw** [comment]
@dpolyakov thank you for your contribution. This is a good idea.

I feel though it needs more of the words translated to Russian. For example the English word "Warning" surely has an equivalent Russian word? And social media names? So if you can translate all the words then I can merge it.

I just noticed my English translation for the word "Infromation" is spelled wrong. I just pushed a commit to fix that.

**Comment by dpolyakov** [comment]
@jhauraw fixed.

Social networks names doesn`t need translation

**Comment by jhauraw** [comment]
@dpolyakov can you please edit the Pull Request and select the "Allow edits from Maintainers box"? Thanks

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by dpolyakov** [comment]
image

**Pull request merged**
